[project]
name = "k8s-workshop-app"
version = "0.1.0"
description = "Minimal Flask SPA demo app for Kubernetes workshop"
requires-python = ">=3.8"

dependencies =[
    "Flask",
    "psycopg2-binary",
]
