services:
  demo-app-container:
    build: 
      context: ../app
      target: prod
      tags:
        - "localhost:5000/demo-app:2"
        - "localhost:5000/demo-app:2.0"
        - "localhost:5000/demo-app:2.0.0"
    image: localhost:5000/demo-app

    environment:
      POSTGRES_HOST: demo-postgres
    ports:
      - "3000:3000"

  demo-postgres:
    image: postgres:17-alpine@sha256:f325a29ec9deb7039c5f07761d77d79d537dac836ecd99f982f6ca5476724604
    environment:
      POSTGRES_PASSWORD: demo
      POSTGRES_USER: demo
      POSTGRES_DB: demo
      POSTGRES_PORT: 5432
    volumes:
      - $HOST_PROJECT_PATH/dbdata:/var/lib/postgresql/data
